server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orderdb
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
